name: miss_misq
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  # Navigation
  go_router: ^15.1.1

  # Use Google Fonts 
  google_fonts: ^6.2.1

  # Show SVGs 
  flutter_svg: ^2.1.0

  # launch URLs
  url_launcher_web: ^2.4.1
  url_launcher: ^6.3.1

  # UI
  data_table_2: ^2.6.0
  fl_chart: ^0.71.0
  dotted_border: ^2.1.0
  toastification: ^3.0.2
  cupertino_icons: ^1.0.8
  skeletonizer: ^2.0.1

  # Networking
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0

  # State Management
  flutter_bloc: ^9.1.1

  # Dependency Injection
  get_it: ^8.0.3

  # Local Storage
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
